Soomin/search
nomoory/next-sandbox pull request #2
Opened 2021-08-16 07:45 UTC by eddhall0821

검색기능
하나의 어절을 한 개의 토큰으로 저장한 뒤 token field와 비교하여 하나라도 일치하는 모든 문서를 리턴합니다.

저장시
모든 필드를 더하여 하나의 문자열로 만들고 어절 단위로 쪼개 token 배열을 생성합니다. (조사를 제거하고 단어 단위로 토큰화 시키는 알고리즘들을 적용하려고 했는데 실패)

2021-08-16 14:29 UTC, nomoory requested changes

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const str1 = string.replace(":", " ").replace(",", " ");
아래 reg 쓰는 로직에서 처리되는 특수문자라 별도로 처리 안해줘도 되지 않을까요?

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const strArray = str.split(" ");
const words = string.split(reg);
으로 대체할 수 있을 것 같네요!

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const dupblicationCheckArray = new Set(strArray);
변수명을 uniqueWords로 하면 어떨까요?

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const uniqueArray = [...dupblicationCheckArray];
spread 연산자를 사용한 이유는 뭔가요?

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  console.log(uniqueArray);
사용하지 않는 console은 (혹은 의도하여 descriptive 하게 만든게 아닌 console) 지워주세요

2021-08-16 14:29 UTC, nomoory commented on components/Search.js
> +const Search = ({ dataStore, field }) => {
search의 대상이 되는 field를 dynamic하게 처리한 것은 좋으나, dataStore를 확인하니 쿼리하는 field가 array 형태여야만 의미가 있는 것 같네요..!
일단은 field를 없에고 무조건 token에서 찾도록 하면 좋을 것 같아요

+token이라는 이름이 명확하지 않게 느껴질 수 있는데 searchTerms 로 바꾸면 어떨까요?

2021-08-16 14:29 UTC, nomoory commented on stores/parentStoreClass/DataStore.js
> +        // .where(field, ">=", text)
불필요한 주석은 지워주세요!

2021-08-16 14:29 UTC, nomoory commented on stores/parentStoreClass/DataStore.js
> +  searchText(field, tags) {
위에도 얘기했는데 일단은  field는 없이 가면 좋을 것 같아요!
유지한다면 targetField가 조금 더 명확할 것 같습니다!

2021-08-16 14:29 UTC, nomoory commented on pages/admin/components/AddForm.js
> +            tempData.token = token;
Tokenizer라는 이름은 생성자 같네요!

함수로 사용할거라면 tokenize로 명명 하는게 더 좋을 것 같고
token이라는 용어보단 searchTerms가 형태에 대한 설명과 목적에 대한 설명이 더 명확한 것 같아서
makeSearchTerms라고 이름 짖는 건 어떨까 싶습니다

2021-08-16 14:29 UTC, nomoory commented on stores/parentStoreClass/DataStore.js
> +  searchText(field, tags) {
searchByText로 이름을 바꾸면 더 좋을 것 같아요!

2021-08-16 14:29 UTC, nomoory commented on components/Search.js
> +  const [tags, setTags] = useState([]);
tag로 한 이유가 있을까요??
로직상 tag 중에 하나라도 있으면 쿼리가 되는 것을 이해할 수 있으나  사용자가 봤을 때는 tag가 늘어나면 어떻게 되는지 명확하지 않은 것 같아서 의견여쭤봐요 :)

2021-08-16 14:29 UTC, nomoory commented on components/Search.js
> +  const handleSearch = async () => {
async가 사용되지 않는 것 같은데 넣어준 이유가 있을까요??

2021-08-16 14:29 UTC, nomoory commented on components/Search.js
> +      console.log("검색어가 너무 많습니다.");
사용자에게 설명할 때는 명확하게 해주는게 좋아요!
ex) '검색어는 최대 ${n}개까지 입력이 가능합니다'

그리고 console.log라 사용자에게 보이진 않겠네요 ㅎㅎ..

2021-08-16 14:29 UTC, nomoory commented on components/Search.js
> +    setLoading(true);
setLoading 관련 로직이 이상한 것 같네요!

search를 요청하면 setLoading(true)가 되고
search가 끝나거나 취소되면 setLoading(false)가 되어야할 것 같은데 이렇게 하면 동작을 제대로 안할 것 같아요~

2021-08-16 14:43 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const str1 = string.replace(":", " ").replace(",", " ");
str1은 : 과 ,를 띄어쓰기로 변환해주고 str은 특수문자 제거라 조금 다르긴한데, str1도 정규식으로 표현할 수 있을 것 같아요

2021-08-16 15:00 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const strArray = str.split(" ");
넵!

2021-08-16 15:00 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const dupblicationCheckArray = new Set(strArray);
넵! 그런데 애초에 Set이라 배열이 아니었네요

2021-08-16 15:01 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const uniqueArray = [...dupblicationCheckArray];
duplicationCheckArray에서 중복을 제거한 Set을 다시 배열로 바꿔주기 위해서 사용했어요

2021-08-16 15:01 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  console.log(uniqueArray);
네!

2021-08-16 15:01 UTC, eddhall0821 commented on pages/admin/components/AddForm.js
> +            tempData.token = token;
네 좋아요!

2021-08-16 15:01 UTC, eddhall0821 commented on components/Search.js
> +  const [tags, setTags] = useState([]);
한 어절씩 저장해서 검색하는 기능이 인스타그램같은 서비스의 해시태그랑 비슷해서 그렇게 지었는데, 다른 좋은 단어가 있을까요? (keywords 라던지..)

2021-08-16 15:01 UTC, eddhall0821 commented on components/Search.js
> +  const handleSearch = async () => {
테스트 하다가 삭제를 안했네요.. 삭제하겠습니다

2021-08-16 15:01 UTC, eddhall0821 commented on components/Search.js
> +      console.log("검색어가 너무 많습니다.");
넵 수정할게요!
그리고 alert로 바꿀게요

2021-08-16 15:01 UTC, eddhall0821 commented on components/Search.js
> +    setLoading(true);
search를 요청하면 setLoading(false)가 되고 끝나면 true가 되네요
반대로 수정할게요!

2021-08-16 15:02 UTC, eddhall0821 commented on stores/parentStoreClass/DataStore.js
> +        // .where(field, ">=", text)
넵!

2021-08-16 15:03 UTC, eddhall0821 commented on stores/parentStoreClass/DataStore.js
> +  searchText(field, tags) {
넵 두개 다 반영할게요! 원래 이름이 searchByText였는데 괜히 바꿨네요

2021-08-16 15:04 UTC, eddhall0821 commented on components/Search.js
> +const Search = ({ dataStore, field }) => {
네 어차피 다른 field에서 사용 불가능한 로직이라, token에서만 찾도록 하는편이 낫겠네요.

2021-08-16 15:04 UTC, eddhall0821 reviewed
꼼꼼하게 검토해주셔서 감사합니다! 수정할게 많네요 ㅎㅎ

2021-08-17 01:29 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const strArray = str.split(" ");
그런데 특수문자 제거를 안하고 바로 split하니까 중복제거하기 전 배열이 너무 길어지네요..

2021-08-17 04:27 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const strArray = str.split(" ");
띄어쓰기에 대한 split이 안되서 그런걸까요? 그렇다면 띄어쓰기에 대해서도 split할 수 있도록 해야할 것 같아요.
왜 결과가 다른지 다르다면 어떻게 로직을 바꿔야하는지 판단해서 로직에 반영해주세요!

2021-08-17 04:29 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const uniqueArray = [...dupblicationCheckArray];
이해했어요! Set을 spread 했을 때 array가 되는 것을 명확하게 해주기 위해
Array.from(str); 을 사용하는 것도 좋은 방법인 것 같아요!

2021-08-17 04:30 UTC, nomoory commented on pages/admin/components/Tokenizer.js
> +  const uniqueArray = [...dupblicationCheckArray];
혹은 removeDuplication()이라는 별도의 함수를 만들고 그 안에서 로직을 처리하도록 하면 코드가 더 명확해질 것 같습니다

2021-08-17 04:31 UTC, nomoory commented on components/Search.js
> +  const [tags, setTags] = useState([]);
tag라는 용어에 대한 피드백은 아니었고 검색을 하는데 왜 tag로 검색이 되는지 싶어 여쭤본거였어요!

한 어절씩 저장하는 이유는 단어로도 검색이 가능하게 하기 위함이어서 (서버단 로직을 위함) 프론트에 tag기능을 넣는 것과는 무관한 것 같아요!

2021-08-18 02:12 UTC, eddhall0821 commented on pages/admin/components/Tokenizer.js
> +  const strArray = str.split(" ");
네 띄어쓰기까지 정규식에 포함해서 수정했어요!

2021-08-18 02:19 UTC, eddhall0821 commented
검색을 기존 tag 방식이 아닌 string으로 받아 배열로 변환하도록 수정
makeSearchTerms 정규식단순화, 중복 제거 함수 추가
기타 불필요한 코드 삭제

2021-08-18 09:27 UTC, nomoory approved these changes
너무 수고하셨습니다 :)

2021-08-18 09:37 UTC, merged